// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/files.proto

package archivist

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Integrity are hashes of byte content.
type Integrity struct {
	Sha512               []byte   `protobuf:"bytes,1,opt,name=sha512,proto3" json:"sha512,omitempty"`
	Blake2B512           []byte   `protobuf:"bytes,2,opt,name=blake2b512,proto3" json:"blake2b512,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Integrity) Reset()         { *m = Integrity{} }
func (m *Integrity) String() string { return proto.CompactTextString(m) }
func (*Integrity) ProtoMessage()    {}
func (*Integrity) Descriptor() ([]byte, []int) {
	return fileDescriptor_132a9b3180f1f907, []int{0}
}

func (m *Integrity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integrity.Unmarshal(m, b)
}
func (m *Integrity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integrity.Marshal(b, m, deterministic)
}
func (m *Integrity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integrity.Merge(m, src)
}
func (m *Integrity) XXX_Size() int {
	return xxx_messageInfo_Integrity.Size(m)
}
func (m *Integrity) XXX_DiscardUnknown() {
	xxx_messageInfo_Integrity.DiscardUnknown(m)
}

var xxx_messageInfo_Integrity proto.InternalMessageInfo

func (m *Integrity) GetSha512() []byte {
	if m != nil {
		return m.Sha512
	}
	return nil
}

func (m *Integrity) GetBlake2B512() []byte {
	if m != nil {
		return m.Blake2B512
	}
	return nil
}

// Blob is an archived collection of bytes.
type Blob struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 uint64               `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Integrity            *Integrity           `protobuf:"bytes,3,opt,name=integrity,proto3" json:"integrity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_132a9b3180f1f907, []int{1}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blob) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Blob) GetModTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModTime
	}
	return nil
}

func (m *Blob) GetIntegrity() *Integrity {
	if m != nil {
		return m.Integrity
	}
	return nil
}

type Filesystem struct {
	Paths                map[string]string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Filesystem) Reset()         { *m = Filesystem{} }
func (m *Filesystem) String() string { return proto.CompactTextString(m) }
func (*Filesystem) ProtoMessage()    {}
func (*Filesystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_132a9b3180f1f907, []int{2}
}

func (m *Filesystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filesystem.Unmarshal(m, b)
}
func (m *Filesystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filesystem.Marshal(b, m, deterministic)
}
func (m *Filesystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filesystem.Merge(m, src)
}
func (m *Filesystem) XXX_Size() int {
	return xxx_messageInfo_Filesystem.Size(m)
}
func (m *Filesystem) XXX_DiscardUnknown() {
	xxx_messageInfo_Filesystem.DiscardUnknown(m)
}

var xxx_messageInfo_Filesystem proto.InternalMessageInfo

func (m *Filesystem) GetPaths() map[string]string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func init() {
	proto.RegisterType((*Integrity)(nil), "archivist.v1.Integrity")
	proto.RegisterType((*Blob)(nil), "archivist.v1.Blob")
	proto.RegisterType((*Filesystem)(nil), "archivist.v1.Filesystem")
	proto.RegisterMapType((map[string]string)(nil), "archivist.v1.Filesystem.PathsEntry")
}

func init() { proto.RegisterFile("proto/files.proto", fileDescriptor_132a9b3180f1f907) }

var fileDescriptor_132a9b3180f1f907 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x41, 0x4f, 0xc2, 0x30,
	0x18, 0x4d, 0xc7, 0x40, 0xf7, 0x41, 0x8c, 0x36, 0x46, 0x17, 0x0e, 0x82, 0x78, 0xe1, 0xd4, 0x85,
	0x19, 0x12, 0xf4, 0x88, 0xd1, 0xc4, 0x9b, 0x69, 0x3c, 0x79, 0x31, 0x1d, 0x2b, 0x5b, 0xc3, 0x46,
	0x97, 0xb5, 0x60, 0xe6, 0xcd, 0x7f, 0xe1, 0xcf, 0x35, 0xed, 0x80, 0xe1, 0xed, 0xbd, 0xef, 0xbd,
	0xb7, 0xbd, 0x57, 0xb8, 0x28, 0x4a, 0xa9, 0x65, 0xb0, 0x14, 0x19, 0x57, 0xc4, 0x62, 0xdc, 0x63,
	0xe5, 0x22, 0x15, 0x5b, 0xa1, 0x34, 0xd9, 0x4e, 0xfa, 0x83, 0x44, 0xca, 0x24, 0xe3, 0x81, 0xd5,
	0xa2, 0xcd, 0x32, 0xd0, 0x22, 0xe7, 0x4a, 0xb3, 0xbc, 0xa8, 0xed, 0xa3, 0x27, 0xf0, 0x5e, 0xd7,
	0x9a, 0x27, 0xa5, 0xd0, 0x15, 0xbe, 0x82, 0x8e, 0x4a, 0xd9, 0x74, 0x12, 0xfa, 0x68, 0x88, 0xc6,
	0x3d, 0xba, 0x63, 0xf8, 0x06, 0x20, 0xca, 0xd8, 0x8a, 0x87, 0x91, 0xd1, 0x1c, 0xab, 0x1d, 0x5d,
	0x46, 0xbf, 0x08, 0xdc, 0x79, 0x26, 0x23, 0x7c, 0x06, 0x8e, 0x88, 0x6d, 0xd8, 0xa3, 0x8e, 0x88,
	0x31, 0x06, 0x57, 0x89, 0x6f, 0x6e, 0x23, 0x2e, 0xb5, 0x18, 0x4f, 0xe1, 0x34, 0x97, 0xf1, 0xa7,
	0x29, 0xe2, 0xbb, 0x43, 0x34, 0xee, 0x86, 0x7d, 0x52, 0xb7, 0x24, 0xfb, 0x96, 0xe4, 0x7d, 0xdf,
	0x92, 0x9e, 0xe4, 0x32, 0x36, 0x0c, 0x4f, 0xc1, 0x13, 0xfb, 0xa2, 0x7e, 0xcb, 0xe6, 0xae, 0xc9,
	0xf1, 0x56, 0x72, 0xd8, 0x41, 0x1b, 0xe7, 0xe8, 0x07, 0x01, 0xbc, 0x98, 0xe7, 0xa9, 0x94, 0xe6,
	0x39, 0x7e, 0x80, 0x76, 0xc1, 0x74, 0xaa, 0x7c, 0x34, 0x6c, 0x8d, 0xbb, 0xe1, 0xdd, 0xff, 0x2f,
	0x34, 0x46, 0xf2, 0x66, 0x5c, 0xcf, 0x6b, 0x5d, 0x56, 0xb4, 0x4e, 0xf4, 0x67, 0x00, 0xcd, 0x11,
	0x9f, 0x43, 0x6b, 0xc5, 0xab, 0xdd, 0x54, 0x03, 0xf1, 0x25, 0xb4, 0xb7, 0x2c, 0xdb, 0xd4, 0x63,
	0x3d, 0x5a, 0x93, 0x47, 0x67, 0x86, 0xe6, 0xb7, 0x1f, 0x83, 0x44, 0xe8, 0x74, 0x13, 0x91, 0x85,
	0xcc, 0x03, 0x9d, 0xf2, 0xe2, 0x8b, 0x25, 0x6b, 0x5e, 0x06, 0x87, 0x9f, 0x47, 0x1d, 0x3b, 0xfd,
	0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x82, 0x17, 0x98, 0x94, 0xd1, 0x01, 0x00, 0x00,
}
