// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/index.proto

package archivist

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Index struct {
	Blobs                []*Blob  `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dde39a7f93d1aab, []int{0}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetBlobs() []*Blob {
	if m != nil {
		return m.Blobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Index)(nil), "archivist.Index")
}

func init() { proto.RegisterFile("proto/index.proto", fileDescriptor_2dde39a7f93d1aab) }

var fileDescriptor_2dde39a7f93d1aab = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcc, 0x4b, 0x49, 0xad, 0xd0, 0x03, 0xb3, 0x85, 0x38, 0x13, 0x8b, 0x92, 0x33,
	0x32, 0xcb, 0x32, 0x8b, 0x4b, 0xa4, 0xa0, 0xb2, 0x69, 0x99, 0x39, 0xa9, 0xc5, 0x10, 0x59, 0x25,
	0x3d, 0x2e, 0x56, 0x4f, 0x90, 0x62, 0x21, 0x55, 0x2e, 0xd6, 0xa4, 0x9c, 0xfc, 0xa4, 0x62, 0x09,
	0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x7e, 0x3d, 0xb8, 0x36, 0x3d, 0xa7, 0x9c, 0xfc, 0xa4, 0x20,
	0x88, 0xac, 0x93, 0x62, 0x94, 0x7c, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae,
	0x7e, 0x49, 0x46, 0x6a, 0x41, 0x79, 0x62, 0x7a, 0x5e, 0x6a, 0x91, 0x3e, 0x5c, 0x79, 0x12, 0x1b,
	0xd8, 0x64, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x68, 0xf6, 0x0c, 0x8c, 0x00, 0x00,
	0x00,
}
