name: PR
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
    - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # renovate: tag=v3
      with:
        go-version: '1.17'
    - run: script/test
    - run: script/lint
