name: Periodic Dependency Update
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_PAT }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - uses: thepwagner/action-update-go@multiple-modules
        with:
          log_level: debug
          token: ${{ secrets.MY_GITHUB_PAT }} 
      - uses: thepwagner/action-update-go/dockerurl@multiple-modules
        with:
          log_level: debug
          token: ${{ secrets.MY_GITHUB_PAT }} 
